// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: client_messages_proto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ClientMessagesProto {

  /// <summary>Holder for reflection information generated from client_messages_proto.proto</summary>
  public static partial class ClientMessagesProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for client_messages_proto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientMessagesProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtjbGllbnRfbWVzc2FnZXNfcHJvdG8ucHJvdG8SE0NsaWVudE1lc3NhZ2Vz",
            "UHJvdG8aFXRyYW5zZm9ybV9wcm90by5wcm90byKWAQoFTFdQb3MSEQoJVGlt",
            "ZVN0YW1wGAEgASgEEjwKFExDb250cm9sbGVyVHJhbnNmb3JtGAIgASgLMh4u",
            "VHJhbnNmb3JtUHJvdG8uTE9DQUxUUkFOU0ZPUk0SPAoUUkNvbnRyb2xsZXJU",
            "cmFuc2Zvcm0YAyABKAsyHi5UcmFuc2Zvcm1Qcm90by5MT0NBTFRSQU5TRk9S",
            "TSJ3CgZMV0F4ZXMSEQoJVGltZVN0YW1wGAEgASgEEiwKC0xUaHVtYlN0aWNr",
            "GAIgASgLMhcuVHJhbnNmb3JtUHJvdG8uVkVDVE9SMhIsCgtSVGh1bWJTdGlj",
            "axgDIAEoCzIXLlRyYW5zZm9ybVByb3RvLlZFQ1RPUjIiOQoHTFdJTlBVVBIM",
            "CgRVVUlEGAEgASgMEg4KBlVwTWFzaxgCIAEoBRIQCghEb3duTWFzaxgDIAEo",
            "BWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TransformProto.TransformProtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientMessagesProto.LWPos), global::ClientMessagesProto.LWPos.Parser, new[]{ "TimeStamp", "LControllerTransform", "RControllerTransform" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientMessagesProto.LWAxes), global::ClientMessagesProto.LWAxes.Parser, new[]{ "TimeStamp", "LThumbStick", "RThumbStick" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientMessagesProto.LWINPUT), global::ClientMessagesProto.LWINPUT.Parser, new[]{ "UUID", "UpMask", "DownMask" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LWPos : pb::IMessage<LWPos>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LWPos> _parser = new pb::MessageParser<LWPos>(() => new LWPos());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LWPos> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientMessagesProto.ClientMessagesProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LWPos() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LWPos(LWPos other) : this() {
      timeStamp_ = other.timeStamp_;
      lControllerTransform_ = other.lControllerTransform_ != null ? other.lControllerTransform_.Clone() : null;
      rControllerTransform_ = other.rControllerTransform_ != null ? other.rControllerTransform_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LWPos Clone() {
      return new LWPos(this);
    }

    /// <summary>Field number for the "TimeStamp" field.</summary>
    public const int TimeStampFieldNumber = 1;
    private ulong timeStamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TimeStamp {
      get { return timeStamp_; }
      set {
        timeStamp_ = value;
      }
    }

    /// <summary>Field number for the "LControllerTransform" field.</summary>
    public const int LControllerTransformFieldNumber = 2;
    private global::TransformProto.LOCALTRANSFORM lControllerTransform_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TransformProto.LOCALTRANSFORM LControllerTransform {
      get { return lControllerTransform_; }
      set {
        lControllerTransform_ = value;
      }
    }

    /// <summary>Field number for the "RControllerTransform" field.</summary>
    public const int RControllerTransformFieldNumber = 3;
    private global::TransformProto.LOCALTRANSFORM rControllerTransform_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TransformProto.LOCALTRANSFORM RControllerTransform {
      get { return rControllerTransform_; }
      set {
        rControllerTransform_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LWPos);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LWPos other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TimeStamp != other.TimeStamp) return false;
      if (!object.Equals(LControllerTransform, other.LControllerTransform)) return false;
      if (!object.Equals(RControllerTransform, other.RControllerTransform)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TimeStamp != 0UL) hash ^= TimeStamp.GetHashCode();
      if (lControllerTransform_ != null) hash ^= LControllerTransform.GetHashCode();
      if (rControllerTransform_ != null) hash ^= RControllerTransform.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TimeStamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TimeStamp);
      }
      if (lControllerTransform_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LControllerTransform);
      }
      if (rControllerTransform_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RControllerTransform);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TimeStamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TimeStamp);
      }
      if (lControllerTransform_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LControllerTransform);
      }
      if (rControllerTransform_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RControllerTransform);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TimeStamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimeStamp);
      }
      if (lControllerTransform_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LControllerTransform);
      }
      if (rControllerTransform_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RControllerTransform);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LWPos other) {
      if (other == null) {
        return;
      }
      if (other.TimeStamp != 0UL) {
        TimeStamp = other.TimeStamp;
      }
      if (other.lControllerTransform_ != null) {
        if (lControllerTransform_ == null) {
          LControllerTransform = new global::TransformProto.LOCALTRANSFORM();
        }
        LControllerTransform.MergeFrom(other.LControllerTransform);
      }
      if (other.rControllerTransform_ != null) {
        if (rControllerTransform_ == null) {
          RControllerTransform = new global::TransformProto.LOCALTRANSFORM();
        }
        RControllerTransform.MergeFrom(other.RControllerTransform);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TimeStamp = input.ReadUInt64();
            break;
          }
          case 18: {
            if (lControllerTransform_ == null) {
              LControllerTransform = new global::TransformProto.LOCALTRANSFORM();
            }
            input.ReadMessage(LControllerTransform);
            break;
          }
          case 26: {
            if (rControllerTransform_ == null) {
              RControllerTransform = new global::TransformProto.LOCALTRANSFORM();
            }
            input.ReadMessage(RControllerTransform);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TimeStamp = input.ReadUInt64();
            break;
          }
          case 18: {
            if (lControllerTransform_ == null) {
              LControllerTransform = new global::TransformProto.LOCALTRANSFORM();
            }
            input.ReadMessage(LControllerTransform);
            break;
          }
          case 26: {
            if (rControllerTransform_ == null) {
              RControllerTransform = new global::TransformProto.LOCALTRANSFORM();
            }
            input.ReadMessage(RControllerTransform);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LWAxes : pb::IMessage<LWAxes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LWAxes> _parser = new pb::MessageParser<LWAxes>(() => new LWAxes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LWAxes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientMessagesProto.ClientMessagesProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LWAxes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LWAxes(LWAxes other) : this() {
      timeStamp_ = other.timeStamp_;
      lThumbStick_ = other.lThumbStick_ != null ? other.lThumbStick_.Clone() : null;
      rThumbStick_ = other.rThumbStick_ != null ? other.rThumbStick_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LWAxes Clone() {
      return new LWAxes(this);
    }

    /// <summary>Field number for the "TimeStamp" field.</summary>
    public const int TimeStampFieldNumber = 1;
    private ulong timeStamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TimeStamp {
      get { return timeStamp_; }
      set {
        timeStamp_ = value;
      }
    }

    /// <summary>Field number for the "LThumbStick" field.</summary>
    public const int LThumbStickFieldNumber = 2;
    private global::TransformProto.VECTOR2 lThumbStick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TransformProto.VECTOR2 LThumbStick {
      get { return lThumbStick_; }
      set {
        lThumbStick_ = value;
      }
    }

    /// <summary>Field number for the "RThumbStick" field.</summary>
    public const int RThumbStickFieldNumber = 3;
    private global::TransformProto.VECTOR2 rThumbStick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TransformProto.VECTOR2 RThumbStick {
      get { return rThumbStick_; }
      set {
        rThumbStick_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LWAxes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LWAxes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TimeStamp != other.TimeStamp) return false;
      if (!object.Equals(LThumbStick, other.LThumbStick)) return false;
      if (!object.Equals(RThumbStick, other.RThumbStick)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TimeStamp != 0UL) hash ^= TimeStamp.GetHashCode();
      if (lThumbStick_ != null) hash ^= LThumbStick.GetHashCode();
      if (rThumbStick_ != null) hash ^= RThumbStick.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TimeStamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TimeStamp);
      }
      if (lThumbStick_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LThumbStick);
      }
      if (rThumbStick_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RThumbStick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TimeStamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TimeStamp);
      }
      if (lThumbStick_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LThumbStick);
      }
      if (rThumbStick_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RThumbStick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TimeStamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimeStamp);
      }
      if (lThumbStick_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LThumbStick);
      }
      if (rThumbStick_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RThumbStick);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LWAxes other) {
      if (other == null) {
        return;
      }
      if (other.TimeStamp != 0UL) {
        TimeStamp = other.TimeStamp;
      }
      if (other.lThumbStick_ != null) {
        if (lThumbStick_ == null) {
          LThumbStick = new global::TransformProto.VECTOR2();
        }
        LThumbStick.MergeFrom(other.LThumbStick);
      }
      if (other.rThumbStick_ != null) {
        if (rThumbStick_ == null) {
          RThumbStick = new global::TransformProto.VECTOR2();
        }
        RThumbStick.MergeFrom(other.RThumbStick);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TimeStamp = input.ReadUInt64();
            break;
          }
          case 18: {
            if (lThumbStick_ == null) {
              LThumbStick = new global::TransformProto.VECTOR2();
            }
            input.ReadMessage(LThumbStick);
            break;
          }
          case 26: {
            if (rThumbStick_ == null) {
              RThumbStick = new global::TransformProto.VECTOR2();
            }
            input.ReadMessage(RThumbStick);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TimeStamp = input.ReadUInt64();
            break;
          }
          case 18: {
            if (lThumbStick_ == null) {
              LThumbStick = new global::TransformProto.VECTOR2();
            }
            input.ReadMessage(LThumbStick);
            break;
          }
          case 26: {
            if (rThumbStick_ == null) {
              RThumbStick = new global::TransformProto.VECTOR2();
            }
            input.ReadMessage(RThumbStick);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LWINPUT : pb::IMessage<LWINPUT>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LWINPUT> _parser = new pb::MessageParser<LWINPUT>(() => new LWINPUT());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LWINPUT> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientMessagesProto.ClientMessagesProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LWINPUT() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LWINPUT(LWINPUT other) : this() {
      uUID_ = other.uUID_;
      upMask_ = other.upMask_;
      downMask_ = other.downMask_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LWINPUT Clone() {
      return new LWINPUT(this);
    }

    /// <summary>Field number for the "UUID" field.</summary>
    public const int UUIDFieldNumber = 1;
    private pb::ByteString uUID_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString UUID {
      get { return uUID_; }
      set {
        uUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "UpMask" field.</summary>
    public const int UpMaskFieldNumber = 2;
    private int upMask_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UpMask {
      get { return upMask_; }
      set {
        upMask_ = value;
      }
    }

    /// <summary>Field number for the "DownMask" field.</summary>
    public const int DownMaskFieldNumber = 3;
    private int downMask_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DownMask {
      get { return downMask_; }
      set {
        downMask_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LWINPUT);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LWINPUT other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UUID != other.UUID) return false;
      if (UpMask != other.UpMask) return false;
      if (DownMask != other.DownMask) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UUID.Length != 0) hash ^= UUID.GetHashCode();
      if (UpMask != 0) hash ^= UpMask.GetHashCode();
      if (DownMask != 0) hash ^= DownMask.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UUID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(UUID);
      }
      if (UpMask != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UpMask);
      }
      if (DownMask != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(DownMask);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UUID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(UUID);
      }
      if (UpMask != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UpMask);
      }
      if (DownMask != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(DownMask);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UUID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(UUID);
      }
      if (UpMask != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UpMask);
      }
      if (DownMask != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DownMask);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LWINPUT other) {
      if (other == null) {
        return;
      }
      if (other.UUID.Length != 0) {
        UUID = other.UUID;
      }
      if (other.UpMask != 0) {
        UpMask = other.UpMask;
      }
      if (other.DownMask != 0) {
        DownMask = other.DownMask;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UUID = input.ReadBytes();
            break;
          }
          case 16: {
            UpMask = input.ReadInt32();
            break;
          }
          case 24: {
            DownMask = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UUID = input.ReadBytes();
            break;
          }
          case 16: {
            UpMask = input.ReadInt32();
            break;
          }
          case 24: {
            DownMask = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
